corner-radius = 4;
round-borders = 1;
round-borders-rule = [
  "3:class_g      = 'XTerm'",
  "3:class_g      = 'URxvt'",
  #"10:class_g     = 'Alacritty'",
  "15:class_g     = 'Signal'"
];


shadow = false;
shadow-radius = 12;
shadow-opacity = 0.75;
shadow-offset-x = -15;
shadow-offset-y = -15;

shadow-exclude = [
  "name = 'Notification'",
  "class_g = 'Conky'",
  "class_g ?= 'Notify-osd'",
  "class_g = 'Cairo-clock'",
  "class_g = 'slop'",
  "class_g = 'Polybar'",
  "_GTK_FRAME_EXTENTS@:c"
];

fading = true;
fade-in-step = 0.015;
fade-out-step = 0.03;
fade-delta = 10;

fade-exclude = [
  #"class_g = 'slop'"   # maim
]

