[colors]
;background = #aa1a1b26
;foreground = #ffffff
;foreground-alt = #eeeeee
background = #1a1b26
foreground = #565f89
foreground-alt = #8F8F8F
module-fg = #FFFFFF
primary = #363D4D
secondary = #363D4D
alternate = #7cb342

red = #f7768e
oracle = #ff9e64
oracle-alt = #e0af68
green = #9ece6a
blue = #2ac3de
blue-alt = #7dcfff
blue2 = #7aa2f7
purple = #bb9af7
dark = #1a1b26
gray = #565f89
gray-alt = #414868
white = #cfc9c2
