

;; =============================
;; INCLUDES
;; =============================

include-file = ~/.config/polybar/colors.ini
include-file = ~/.config/polybar/modules.ini



;; =============================
;; BAR SETTINGS
;; =============================

[bar/bar]
fixed-center = true
width = 100%
height = 24pt

background = ${colors.background}
foreground = ${colors.foreground}

font-0 = "BlexMono NF:size=10;2"
font-1 = "BlexMono NF:size=10;2"

line-size = 3pt
border-size = 10pt
border-bottom-size = 0
border-color = #00000000
radius = 6

padding-left = 1
padding-right = 1
module-margin = 1

modules-left = icon title
modules-center = workspaces
modules-right = pulseaudio date cpu memory battery network powermenu

separator =
cursor-click = pointer
cursor-scroll = ns-resize
enable-ipc = true


[settings]
screenchange-reload = true
pseudo-transparency = true


; vim:ft=dosini
