[module/icon]
type = custom/script
label = " "
exec = " "
format = <label>
tail = true
format-foreground = ${colors.blue}


[module/title]
type = internal/xwindow
label = "| %title:0:30:...%"



[module/pulseaudio]
type = internal/pulseaudio
format-volume-prefix = "墳 "
format-volume-prefix-foreground = ${colors.white}
format-volume = <label-volume>
label-volume = %percentage%%
label-muted = muted
label-muted-foreground = ${colors.disabled}



[module/memory]
type = internal/memory
interval = 2
format-prefix = " "
format-prefix-foreground = ${colors.blue2}
label = %percentage_used:2%%



[module/cpu]
type = internal/cpu
interval = 2
format-prefix = " "
format-prefix-foreground = ${colors.green}
label = %percentage:2%%



[module/date]
type = internal/date
interval = 1
format-prefix = " "
format-prefix-foreground = ${colors.oracle}
date = %H:%M
date-alt = %Y-%m-%d %H:%M:%S
label = %date%



[module/powermenu]
label-open = " "
label-close = " "
type = custom/menu
menu-0-0 = "    "
menu-0-0-exec = poweroff
menu-0-1 = "    "
menu-0-1-exec = systemctl reboot
menu-0-2 = "  ⏾  "
menu-0-2-exec = systemctl suspend



[module/workspaces]
type = internal/xworkspaces
pin-workspaces = true
enable-click = true
enable-scroll = true
icon-0 = 1;
icon-1 = 2;
icon-2 = 3;
icon-3 = 4;
icon-4 = 5;
icon-5 = 6;
icon-default = 
format = <label-state>
label-monitor = %name%
label-active = 
;label-active-foreground = ${color.foreground-alt}
label-active-foreground = ${colors.blue2}
label-occupied = 
label-occupied-foreground = ${colors.foreground-alt}
label-urgent = 
label-urgent-foreground = ${colors.red}
label-empty = 
label-empty-foreground = ${colors.foreground-alt}
label-active-padding = 1
label-urgent-padding = 1
label-occupied-padding = 1
label-empty-padding = 1




[module/network]
type = internal/network
interface = wlo1
interval = 1.0
accumulate-stats = true
unknown-as-up = true
format-connected = <ramp-signal> <label-connected>
format-connected-foreground = ${colors.green}
;format-connected-padding = 1
format-disconnected = <label-disconnected>
format-disconnected-prefix = ﲁ
;format-disconnected-padding = 1
label-connected = "%{A1:networkmanager_dmenu &:}%essid% %{A}"
label-disconnected = "%{A1:networkmanager_dmenu &:} Offline %{A}"
ramp-signal-0 = 說
ramp-signal-1 = 說
ramp-signal-2 = 說




[module/battery]
type = internal/battery
full-at = 99
battery = BAT1
adapter = ACAD
poll-interval = 2
time-format = %H:%M
format-charging = <animation-charging> <label-charging>
;format-charging-foreground = ${colors.shade4}
format-charging-padding = 1
format-discharging = <ramp-capacity> <label-discharging>
;format-discharging-foreground = ${colors.gray}
format-discharging-padding = 1
format-full = <label-full>
format-full-prefix = 
;format-full-background = ${colors.shade4}
format-full-padding = 1
label-charging = " %percentage%%"
label-discharging = " %percentage%%"
label-full = " Full "
ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 
animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-3 = 
animation-charging-4 = 
animation-charging-framerate = 750
