require("byandrev.options")
require("byandrev.colorscheme")
require("byandrev.plugins")

-- require("byandrev.mason")
require("byandrev.lsp")
require("byandrev.preserve-cursor")
require("byandrev.lualine")
require("byandrev.keymaps")
require("byandrev.autopairs")
require("byandrev.tree")
